In [4]:
import numpy as np

In [5]:
new=np.genfromtxt(r"C:\Users\GOPI\Downloads\train_extended.csv",delimiter=",",skip_header=1)

In [6]:
new

array([[ 1.575     ,  1.225     ,  0.375     , ...,  6.3219385 ,
         9.63883   , 10.        ],
       [ 1.2375    ,  1.        ,  0.375     , ...,  3.798833  ,
         7.654365  , 19.        ],
       [ 1.45      ,  1.1625    ,  0.4125    , ...,  7.01650125,
         7.257472  , 11.        ],
       ...,
       [ 1.125     ,  0.9125    ,  0.2875    , ...,  1.984465  ,
         3.118445  ,  7.        ],
       [ 1.625     ,  1.275     ,  0.4125    , ...,  7.86698625,
        10.489315  , 11.        ],
       [ 1.5875    ,  1.25      ,  0.3875    , ...,  7.38504475,
         8.788345  , 11.        ]])

In [7]:
length=new[:,0:1]

In [8]:
length

array([[1.575 ],
       [1.2375],
       [1.45  ],
       ...,
       [1.125 ],
       [1.625 ],
       [1.5875]])

In [9]:
diameter=new[:,1:2]

In [10]:
diameter

array([[1.225 ],
       [1.    ],
       [1.1625],
       ...,
       [0.9125],
       [1.275 ],
       [1.25  ]])

In [11]:
height=new[:,2:3]

In [12]:
height

array([[0.375 ],
       [0.375 ],
       [0.4125],
       ...,
       [0.2875],
       [0.4125],
       [0.3875]])

In [13]:
weight=new[:,3:4]

In [14]:
weight

array([[31.22697425],
       [21.885814  ],
       [28.25027675],
       ...,
       [10.886208  ],
       [33.89182725],
       [34.37376875]])

In [15]:
shuckedw=new[:,4:5]

In [16]:
shuckedw

array([[12.303683  ],
       [ 7.654365  ],
       [11.12717875],
       ...,
       [ 4.9044635 ],
       [13.19669225],
       [17.22232125]])

In [17]:
visceraw=new[:,5:6]

In [18]:
visceraw

array([[6.3219385 ],
       [3.798833  ],
       [7.01650125],
       ...,
       [1.984465  ],
       [7.86698625],
       [7.38504475]])

In [19]:
shellw=new[:,6:7]

In [20]:
shellw

array([[ 9.63883 ],
       [ 7.654365],
       [ 7.257472],
       ...,
       [ 3.118445],
       [10.489315],
       [ 8.788345]])

In [21]:
age=new[:,7:8]

In [22]:
age

array([[10.],
       [19.],
       [11.],
       ...,
       [ 7.],
       [11.],
       [11.]])

In [23]:
#1. max and min length
np.max(new)

80.10151225

In [24]:
np.min(new)

0.0

In [25]:
#2. difference between max and min length
np.max(new)-np.min(new)

80.10151225

In [26]:
#3. column wise average
np.average(new,axis=0)

array([ 1.31244808,  1.02032036,  0.34602787, 23.12343631,  9.98937025,
        4.99318096,  6.63422915,  9.950615  ])

In [27]:
#4. find out the age whose height is greatherthan 0.4
age

array([[10.],
       [19.],
       [11.],
       ...,
       [ 7.],
       [11.],
       [11.]])

In [28]:
[height>0.4]

[array([[False],
        [False],
        [ True],
        ...,
        [False],
        [ True],
        [False]])]

In [29]:
age[height>0.4]

array([11., 14., 13., ..., 11., 11., 11.])

In [30]:
#5. average height and weight whose age=10

In [31]:
age

array([[10.],
       [19.],
       [11.],
       ...,
       [ 7.],
       [11.],
       [11.]])

In [32]:
a=height[age==10]

In [33]:
a

array([0.375 , 0.4   , 0.3375, ..., 0.3125, 0.3875, 0.3875])

In [34]:
np.average(a)

0.3833672856539947

In [35]:
b=weight[age==10]

In [36]:
b

array([31.22697425, 28.33532525, 18.313777  , ..., 26.18076325,
       30.46153775, 34.9549335 ])

In [37]:
np.average(b)

28.243308450511314

In [38]:
#6.total shell weight

In [39]:
shellw

array([[ 9.63883 ],
       [ 7.654365],
       [ 7.257472],
       ...,
       [ 3.118445],
       [10.489315],
       [ 8.788345]])

In [40]:
np.sum(shellw)

1326845.8295214002

In [91]:
#7. how many persons belong to each and every unique age
x=np.unique(age,return_counts=True)

In [95]:
x

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
        27., 29.]),
 array([   46,    42,   625,  2787,  5475, 12450, 18276, 26818, 32906,
        30803, 23457, 12717, 10037,  6352,  4831,  3191,  2705,  1953,
         1591,  1206,   721,   296,   352,   110,    51,    46,    99,
           57], dtype=int64))

In [43]:
#8. difference between shucked weight and viscera weight
shuckedw

array([[12.303683  ],
       [ 7.654365  ],
       [11.12717875],
       ...,
       [ 4.9044635 ],
       [13.19669225],
       [17.22232125]])

In [44]:
visceraw

array([[6.3219385 ],
       [3.798833  ],
       [7.01650125],
       ...,
       [1.984465  ],
       [7.86698625],
       [7.38504475]])

In [45]:
shuckedw-visceraw

array([[5.9817445],
       [3.855532 ],
       [4.1106775],
       ...,
       [2.9199985],
       [5.329706 ],
       [9.8372765]])

In [46]:
#9. Average height of a person whose age between 14 & 19
height

array([[0.375 ],
       [0.375 ],
       [0.4125],
       ...,
       [0.2875],
       [0.4125],
       [0.3875]])

In [97]:
x=new[new[:,7]>14]

In [98]:
x

array([[ 1.2375    ,  1.        ,  0.375     , ...,  3.798833  ,
         7.654365  , 19.        ],
       [ 1.275     ,  1.        ,  0.3875    , ...,  5.85417175,
         6.9456275 , 16.        ],
       [ 1.7       ,  1.3625    ,  0.4375    , ...,  8.2497045 ,
        15.7339725 , 19.        ],
       ...,
       [ 1.8       ,  1.45      ,  0.4375    , ..., 11.566596  ,
        17.56251525, 16.        ],
       [ 1.5375    ,  1.25      ,  0.4125    , ...,  7.484268  ,
        15.4504775 , 21.        ],
       [ 1.4375    ,  1.125     ,  0.375     , ...,  5.10291   ,
         7.087375  , 15.        ]])

In [99]:
y=x[x[:,7]<19]

In [100]:
y

array([[ 1.275     ,  1.        ,  0.3875    , ...,  5.85417175,
         6.9456275 , 16.        ],
       [ 1.425     ,  1.15      ,  0.3625    , ...,  5.8683465 ,
         7.5126175 , 17.        ],
       [ 1.5625    ,  1.1625    ,  0.4       , ...,  5.85417175,
         9.355335  , 15.        ],
       ...,
       [ 1.3       ,  1.        ,  0.35      , ...,  4.89028875,
         7.37087   , 15.        ],
       [ 1.8       ,  1.45      ,  0.4375    , ..., 11.566596  ,
        17.56251525, 16.        ],
       [ 1.4375    ,  1.125     ,  0.375     , ...,  5.10291   ,
         7.087375  , 15.        ]])

In [101]:
z=y[:,3]

In [102]:
z

array([21.55979475, 25.10348225, 31.22697425, ..., 19.83047525,
       70.66112875, 26.2799865 ])

In [103]:
np.mean(z)

32.11337167476735

In [48]:
#10. Average weight if we include shueld weight ,viscera weight and shell weight.

In [49]:
x=np.average(shellw)

In [50]:
x

6.634229147607001

In [51]:
y=np.average(shuckedw)

In [52]:
y

9.989370248049001

In [53]:
z=np.average(visceraw)

In [54]:
z

4.993180956748749

In [55]:
(x+y+z)/3

7.205593450801583

In [56]:
#              second sheet

In [57]:
new1=np.genfromtxt(r"C:\Users\GOPI\Downloads\tipsf (1).csv",delimiter=",",skip_header=1)

In [58]:
new1

array([[  0.  ,  16.99,   1.01, ...,   1.  ,   0.  ,   2.  ],
       [  1.  ,  10.34,   1.66, ...,   1.  ,   0.  ,   3.  ],
       [  2.  ,  21.01,   3.5 , ...,   1.  ,   0.  ,   3.  ],
       ...,
       [241.  ,  22.67,   2.  , ...,   0.  ,   0.  ,   2.  ],
       [242.  ,  17.82,   1.75, ...,   0.  ,   0.  ,   2.  ],
       [243.  ,  18.78,   3.  , ...,   2.  ,   0.  ,   2.  ]])

In [59]:
totalbill=new1[:,1:2]

In [60]:
totalbill

array([[16.99],
       [10.34],
       [21.01],
       [23.68],
       [24.59],
       [25.29],
       [ 8.77],
       [26.88],
       [15.04],
       [14.78],
       [10.27],
       [35.26],
       [15.42],
       [18.43],
       [14.83],
       [21.58],
       [10.33],
       [16.29],
       [16.97],
       [20.65],
       [17.92],
       [20.29],
       [15.77],
       [39.42],
       [19.82],
       [17.81],
       [13.37],
       [12.69],
       [21.7 ],
       [19.65],
       [ 9.55],
       [18.35],
       [15.06],
       [20.69],
       [17.78],
       [24.06],
       [16.31],
       [16.93],
       [18.69],
       [31.27],
       [16.04],
       [17.46],
       [13.94],
       [ 9.68],
       [30.4 ],
       [18.29],
       [22.23],
       [32.4 ],
       [28.55],
       [18.04],
       [12.54],
       [10.29],
       [34.81],
       [ 9.94],
       [25.56],
       [19.49],
       [38.01],
       [26.41],
       [11.24],
       [48.27],
       [20.29],
       [13.81],
       [

In [61]:
tip=new1[:,2:3]

In [62]:
tip

array([[ 1.01],
       [ 1.66],
       [ 3.5 ],
       [ 3.31],
       [ 3.61],
       [ 4.71],
       [ 2.  ],
       [ 3.12],
       [ 1.96],
       [ 3.23],
       [ 1.71],
       [ 5.  ],
       [ 1.57],
       [ 3.  ],
       [ 3.02],
       [ 3.92],
       [ 1.67],
       [ 3.71],
       [ 3.5 ],
       [ 3.35],
       [ 4.08],
       [ 2.75],
       [ 2.23],
       [ 7.58],
       [ 3.18],
       [ 2.34],
       [ 2.  ],
       [ 2.  ],
       [ 4.3 ],
       [ 3.  ],
       [ 1.45],
       [ 2.5 ],
       [ 3.  ],
       [ 2.45],
       [ 3.27],
       [ 3.6 ],
       [ 2.  ],
       [ 3.07],
       [ 2.31],
       [ 5.  ],
       [ 2.24],
       [ 2.54],
       [ 3.06],
       [ 1.32],
       [ 5.6 ],
       [ 3.  ],
       [ 5.  ],
       [ 6.  ],
       [ 2.05],
       [ 3.  ],
       [ 2.5 ],
       [ 2.6 ],
       [ 5.2 ],
       [ 1.56],
       [ 4.34],
       [ 3.51],
       [ 3.  ],
       [ 1.5 ],
       [ 1.76],
       [ 6.73],
       [ 3.21],
       [ 2.  ],
       [

In [63]:
sex=new1[:,3:4]

In [64]:
sex

array([[0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],

In [65]:
smoker=new1[:,4:5]

In [66]:
smoker

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],

In [67]:
day=new1[:,5:6]

In [68]:
day

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],

In [69]:
time=new1[:,6:7]

In [70]:
time

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],

In [71]:
size=new1[:,7:8]

In [72]:
size

array([[2.],
       [3.],
       [3.],
       [2.],
       [4.],
       [4.],
       [2.],
       [4.],
       [2.],
       [2.],
       [2.],
       [4.],
       [2.],
       [4.],
       [2.],
       [2.],
       [3.],
       [3.],
       [3.],
       [3.],
       [2.],
       [2.],
       [2.],
       [4.],
       [2.],
       [4.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [4.],
       [2.],
       [4.],
       [2.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [2.],
       [2.],
       [2.],
       [4.],
       [2.],
       [2.],
       [4.],
       [3.],
       [2.],
       [2.],
       [2.],
       [4.],
       [2.],
       [4.],
       [2.],
       [4.],
       [2.],
       [2.],
       [4.],
       [2.],
       [2.],
       [2.],
       [4.],
       [3.],
       [3.],
       [2.],
       [1.],
       [2.],
       [2.],
       [2.],
       [3.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],

In [73]:
#1. what is the total bill value
a=np.sum(totalbill)

In [74]:
a

4827.77

In [75]:
#2. What is the total tip value
b=np.sum(tip)

In [76]:
b

731.5799999999999

In [89]:
#3. count how many sunday,saterday,thuresday,friday are there
day

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],

In [94]:
np.unique(day,return_counts=True) 

(array([0., 1., 2., 3.]), array([87, 76, 62, 19], dtype=int64))

In [78]:
#4. how many smokers are there
np.sum(smoker)

93.0

In [79]:
#5. what is the average tip given by famale and male
np.average(tip)

2.99827868852459

In [80]:
#6.how much amount spend by male and female
(a+b)/2

2779.675

In [81]:
#7. what is the max and min tip given
np.max(tip)

10.0

In [82]:
np.min(tip)

1.0

In [83]:
#8. how many male and female going for dinner and lunch
len(sex)

244

In [84]:
#9. Find out the average size
np.average(size)

2.569672131147541

In [85]:
#10. how many male smokers and female smokers are there
male=len(sex)-np.sum(sex)

In [86]:
male

87.0

In [87]:
female=len(sex)-male

In [88]:
female

157.0