In [95]:
import numpy as np

In [96]:
#1 write a program to creat a 5-dim array with all zeros and ones

In [97]:
y=np.array([1,1,1],ndmin=5)

In [98]:
y

array([[[[[1, 1, 1]]]]])

In [99]:
y=np.array([0,0,0,0,0],ndmin=5)

In [100]:
y

array([[[[[0, 0, 0, 0, 0]]]]])

In [101]:
#2. write a program to creat any array of shape 10(0),10(1), and 10(5) in row 12 and 3 which creat a new array of shape(3,10)

In [102]:
x=np.array([[np.zeros(10)],[np.ones(10)],[np.full(10,5)]])

In [103]:
x

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]]])

In [104]:
x.shape

(3, 1, 10)

In [105]:
#3.Write a program to creat a 3*4 matrix filled with values from 10 to 21

In [106]:
z=np.arange(10,22).reshape(3,4)

In [107]:
z

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [108]:
z.shape

(3, 4)

In [109]:
#4. write a program to creat a 10 *10 zero matrix with elements on the main diagonal equal to 0,1,2,3,4,5,6,7,8,9

In [110]:
d=np.diag([0,1,2,3,4,5,6,7,8,9])

In [111]:
d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [112]:
d.shape

(10, 10)

In [113]:
#5. write a program to creat a 4*4 array by swaping first and last ,second and third columns

In [114]:
z=np.arange(1,17).reshape(4,4)

In [115]:
z

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [116]:
z[::-1,::]

array([[13, 14, 15, 16],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [117]:
#6.write a program to reverse an array ( the first element becomes the last)

In [118]:
r=np.arange(12,28)

In [119]:
r

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [120]:
r[::-1]

array([27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12])

In [121]:
#7. write a program to access all elements >30 and <80 and multiples of 5 from an array of shape 10*10.
# elements range from 1 to 100

In [122]:
a=np.arange(1,101).reshape(10,10)


In [123]:
b=a[(a>30) & (a<80) & (a%5==0)]

In [124]:
b

array([35, 40, 45, 50, 55, 60, 65, 70, 75])

In [125]:
#8.write a program to creat a 2d array with 1 on the border and 0 inside.

In [126]:
np.array([[1,1,1],[1,0,1],[1,1,1]])

array([[1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [127]:
#9. write a program to creat a checkerboard pattern. dont use default array function.

In [128]:
print("checkerboard: \n")
c=np.ones((8,8),dtype=int)

checkerboard: 



In [129]:
c

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [130]:
c[1::2,::2]=0
c[::2,1::2]=0

In [131]:
c

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [132]:
#10.Write a program to find common values between two arrays.

In [133]:
i=0
a1=np.array([10,20,40,60])
a2=np.array([10,30,40,50])
np.intersect1d(a2,a1)


array([10, 40])

In [134]:
#11. write a program to creat an 2d array and then reshape into 1d array

In [135]:
x=np.arange(1,5).reshape(2,2)

In [136]:
x

array([[1, 2],
       [3, 4]])

In [137]:
x.flatten()

array([1, 2, 3, 4])

In [138]:
#12. Write a user defined function for creating a 1d or 2d array from scratch with out using array function

In [141]:
def array_2d(x):
    n=int(input("enter the dimention: "))
    s=len(x)
    if n==1:
        print("array({})".format(x))
    elif n==2:
        print("array([",end="")
        print("[{}]".format(x[0]))
        for y in range(1,s-1):
            print("[{}]".format(x[y]))
            print("])")
l=[]

t=int(input("enter no of elements: "))
for i in range(t):
    a=input("enter the element: ")
    l.append(a)
print(l)
array_2d(l)

enter no of elements: 5
enter the element: 1
enter the element: 2
enter the element: 3
enter the element: 4
enter the element: 5
['1', '2', '3', '4', '5']
enter the dimention: 2
array([[1]
[2]
])
[3]
])
[4]
])
